# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: iDEC Cambridge 2026
email: cambridgeidec2026@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  iDEC Cambridge 2026 wiki and project notes.
baseurl: "/2026_Cambridge" # the subpath of your site, e.g. /blog
url: "https://idec-teams.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: Europe/London

text_skin: default
highlight_theme: default

# Team names, titles and social links
team:
- name: James
  pic: James.jpeg
  course: Year 2 Natural Sciences (Biological)
  email: jy570@cam.ac.uk

- name: Yi Feng
  pic: yf.jpeg
  course: Year 2 Natural Sciences (Biological)
  email: yfl32@cam.ac.uk

- name: Kean Ann
  pic: ka.jpeg  
  course: Year 2 Chemical Engineering and Biotechnology
  email: kat46@cam.ac.uk

- name: Setareh
  pic: setareh.jpeg  
  course: Year 3 Medicine
  email: ss3192@cam.ac.uk

- name: Tomn
  pic: tomn.jpeg
  course: Year 2 Natural Sciences (Biological)
  email: cw978@cam.ac.uk

advisors:
- name: Jarrod
  pic: jarrod-shilts.png

- name: Gabriele
  pic: Default_pfp.jpg

- name: Alanna
  pic: alanna.jpeg

- name: Chun Ting
  pic: chunting.jpeg

- name: John
  pic: Default_pfp.jpg

- name: Amy
  pic: amy.jpg

- name: Alexander
  pic: alex.jpeg

sponsors:
- name: Integrated DNA Technologies
  pic: IDT-Logo.png
  url: https://eu.idtdna.com/page

- name: New England Biolabs
  pic: New_NEB_Logo.png
  url: https://www.neb.com/en-gb


author:
  type: organization
  name: iDEC Cambridge 2026
  email: cambridgeidec2026@gmail.com

# Build settings
theme: jekyll-text-theme
markdown: kramdown
highlighter: rouge
permalink: date
paginate: 8
paginate_path: /page:num

search:
  provider: false
sharing:
  provider: false
comments:
  provider: false
analytics:
  provider: false

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      aside:
        toc: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
